# Needed so we can install snaps
sudo: required
dist: trusty

language: cpp

branches:
  only:
  - staging
  - trying
  - master

install:
  - sudo apt-get -qq update;
  - sudo apt-get -y install lxd/trusty-backports liblxc1/trusty-backports
  - sudo lxd init --auto;
  - sudo apt-get --yes install snapd
  - sudo adduser $USER lxd
  - sg lxd -c 'lxc network create lxdbr0';
  - sg lxd -c 'lxc network attach-profile lxdbr0 default eth0';
  - wget https://cooperteam.net/spread_2017.09.21_amd64.snap
  - sudo snap install --dangerous spread_2017.09.21_amd64.snap

env:
  matrix:
  - SYSTEM=ubuntu-16.04 VARIANT=gcc
  - SYSTEM=ubuntu-17.10 VARIANT=gcc
  - SYSTEM=ubuntu-17.10 VARIANT=clang
  - SYSTEM=fedora-26 VARIANT=gcc

script:
  - sg lxd -c '/snap/bin/spread lxd:$SYSTEM:...:$VARIANT'
